[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
optimizer = true
optimizer_runs = 8000
via-ir = false
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]

[profile.ir]
via-ir = true
