name: Test
on: [pull_request]

env:
  SOLC_VERSION: 0.8.20

jobs:
  contract-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Show forge version
      run: forge --version

    - name: npm install
      run: npm install

    - name: Build and Check sizes
      run: make SOLC_VERSION=${{ env.SOLC_VERSION }} build

    - name: Run tests
      run: make SOLC_VERSION=${{ env.SOLC_VERSION }} TEST_UPGRADEABLE=true test

    - name: Lint
      run: make lint
